"""Generate downloadable HTML and PDF financial reports."""

from __future__ import annotations

from datetime import datetime
from io import BytesIO
from typing import Any


def _fmt_pkr(value: float) -> str:
    return f"PKR {value:,.2f}"


def build_html_report(
    summary: dict[str, Any],
    anomalies: list[dict],
    budget_status: list[dict],
    source_name: str = "Bank Statement",
) -> str:
    """Build a styled HTML report string."""
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    category_rows = "".join(
        f"<tr><td>{cat}</td><td>{_fmt_pkr(amt)}</td></tr>"
        for cat, amt in summary.get("category_breakdown", {}).items()
    )
    anomaly_rows = "".join(
        f"<tr><td>{a.get('Date','')}</td><td>{a.get('Description','')}</td>"
        f"<td>{_fmt_pkr(a.get('Amount', 0))}</td><td>{a.get('Category','')}</td>"
        f"<td>{a.get('Explanation','')}</td></tr>"
        for a in anomalies[:20]
    ) or "<tr><td colspan='5'>No anomalies detected.</td></tr>"
    budget_rows = "".join(
        f"<tr><td>{b['category']}</td><td>{_fmt_pkr(b['budget'])}</td>"
        f"<td>{_fmt_pkr(b['actual'])}</td><td>{b['pct']:.0f}%</td>"
        f"<td>{b['status']}</td></tr>"
        for b in budget_status
    ) or "<tr><td colspan='5'>No budget configured.</td></tr>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>BudgetBuddy AI Report</title>
  <style>
    body {{ font-family: 'Segoe UI', sans-serif; margin: 40px; color: #1e293b; }}
    h1 {{ color: #4f46e5; }}
    h2 {{ color: #334155; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }}
    table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
    th, td {{ border: 1px solid #e2e8f0; padding: 10px; text-align: left; }}
    th {{ background: #f1f5f9; }}
    .metrics {{ display: flex; gap: 20px; flex-wrap: wrap; }}
    .metric {{ background: #f8fafc; padding: 16px 24px; border-radius: 12px; border: 1px solid #e2e8f0; }}
    .metric strong {{ display: block; font-size: 1.4em; color: #4f46e5; }}
    footer {{ margin-top: 40px; color: #94a3b8; font-size: 0.9em; }}
  </style>
</head>
<body>
  <h1>BudgetBuddy AI — Financial Report</h1>
  <p>Source: <strong>{source_name}</strong> · Generated: {generated}</p>

  <h2>Summary</h2>
  <div class="metrics">
    <div class="metric">Total Income<strong>{_fmt_pkr(summary.get('total_income', 0))}</strong></div>
    <div class="metric">Total Expenses<strong>{_fmt_pkr(summary.get('total_expenses', 0))}</strong></div>
    <div class="metric">Net Savings<strong>{_fmt_pkr(summary.get('net_savings', 0))}</strong></div>
    <div class="metric">Daily Avg Expense<strong>{_fmt_pkr(summary.get('daily_average', 0))}</strong></div>
  </div>

  <h2>Spending by Category</h2>
  <table>
    <tr><th>Category</th><th>Amount</th></tr>
    {category_rows}
  </table>

  <h2>Budget vs Actual</h2>
  <table>
    <tr><th>Category</th><th>Budget</th><th>Actual</th><th>Used</th><th>Status</th></tr>
    {budget_rows}
  </table>

  <h2>Flagged Anomalies</h2>
  <table>
    <tr><th>Date</th><th>Description</th><th>Amount</th><th>Category</th><th>Explanation</th></tr>
    {anomaly_rows}
  </table>

  <footer>Generated by BudgetBuddy AI · For academic / personal finance use only.</footer>
</body>
</html>"""


def build_pdf_report(
    summary: dict[str, Any],
    anomalies: list[dict],
    budget_status: list[dict],
    source_name: str = "Bank Statement",
) -> bytes | None:
    """Build PDF bytes using reportlab, or return None if unavailable."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    except ImportError:
        return None

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("BudgetBuddy AI — Financial Report", styles["Title"]))
    story.append(Paragraph(f"Source: {source_name}", styles["Normal"]))
    story.append(Spacer(1, 12))

    summary_data = [
        ["Metric", "Value"],
        ["Total Income", _fmt_pkr(summary.get("total_income", 0))],
        ["Total Expenses", _fmt_pkr(summary.get("total_expenses", 0))],
        ["Net Savings", _fmt_pkr(summary.get("net_savings", 0))],
        ["Daily Avg Expense", _fmt_pkr(summary.get("daily_average", 0))],
    ]
    t = Table(summary_data, colWidths=[200, 200])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4f46e5")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    story.append(t)
    story.append(Spacer(1, 16))

    if budget_status:
        story.append(Paragraph("Budget vs Actual", styles["Heading2"]))
        budget_data = [["Category", "Budget", "Actual", "Used", "Status"]]
        for b in budget_status:
            budget_data.append([
                b["category"],
                _fmt_pkr(b["budget"]),
                _fmt_pkr(b["actual"]),
                f"{b['pct']:.0f}%",
                b["status"],
            ])
        bt = Table(budget_data)
        bt.setStyle(TableStyle([("GRID", (0, 0), (-1, -1), 0.5, colors.grey)]))
        story.append(bt)

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
